# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('wireless-point-to-point-example', ['wireless-point-to-point', 'core', 'internet', 'applications', 'mobility', 'propagation'])
    obj.source = 'wireless-point-to-point-example.cc'

    obj = bld.create_ns3_program('wppp-distributed',
                                 ['wireless-point-to-point', 'internet', 'mobility', 'applications', 'core', 'network', 'propagation'])
    obj.source = 'wppp-distributed.cc'
